condense_wildcard_suffixes = true
edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
hard_tabs = true
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
group_imports = "StdExternalCrate"
tab_spaces = 4
